#!/bin/bash
set -eu

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER $AIRFLOW_DB_USER WITH PASSWORD '$AIRFLOW_DB_PASSWORD';
    CREATE DATABASE $AIRFLOW_DB;
    GRANT ALL PRIVILEGES ON DATABASE $AIRFLOW_DB TO $AIRFLOW_DB_USER;
    GRANT ALL PRIVILEGES ON SCHEMA public TO $AIRFLOW_DB_USER;
    ALTER DATABASE $AIRFLOW_DB OWNER TO $AIRFLOW_DB_USER;
EOSQL